### ISSUE TITLE
Manual + vignette PDF?

### ISSUE THREAD

**Issue by sigven** [wesleyburr/subMaldi#4]
Hi,

Would it be possible to generate PDF versions of the manual + vignette and add them to the repo? E.g. using `devtools::build_manual()` and `devtools::build_vignettes()`. It is now somewhat hard to access the documentation of functions/workflows etc. 

kind regards,
Sigve

**Comment by wesleyburr** [comment]
Added the docs directory, which has the HTML (default) and PDF (manually exported, not the best quality) copies of the vignettes and package documentation. Normally installing the package on a system will render these vignettes and make them available to the user, so they aren't shipped with the package.
